## IMPORTANT!
## The Postgres and Elasticsearch containers pull in volumes from
## data containers called 'postgres_data' and 'elasticsearch_data'.
## This compose setup does not create those and you need to do it
## manually:
## docker create -v /var/lib/postgresql/data --name postgres_data postgres:9.4.2 /bin/true
## docker create -v /usr/share/elasticsearch/data --name elasticsearch_data elasticsearch:1.7 /bin/true
---
postgres:
  image: postgres:9.4.2
  expose:
    - "5432"
  volumes:
    - ./docker_compose/postgres-setup:/docker-entrypoint-initdb.d
  volumes_from:
    - postgres_data
  environment:
    POSTGRES_PASSWORD: plannr

elasticsearch:
  image: elasticsearch:1.7
  volumes_from:
    - elasticsearch_data
  ports:
    - "9200:9200"
    - "9300:9300"
  command: '-Des.http.cors.enabled=true'

logstash:
  image: logstash:1.5
  ports:
    - "9998:9998"
    - "9999:9999/udp"
  volumes:
    - ./docker_compose/logstash:/config-dir
  links:
    - elasticsearch:elasticsearch
  command: '-f /config-dir/logstash.conf'

kibana:
  image: kibana:4.1
  links:
    - elasticsearch:elasticsearch
  ports:
    - 5601:5601

web:
  build: ./
  volumes:
    - .:/home/app/plannr
  links:
    - postgres:postgres
    - elasticsearch:elasticsearch
    - logstash:logstash
  ports:
    - "3000:3000"
  environment:
    DATABASE_URL: postgres://postgres:plannr@postgres:5432/plannr_development?pool=5&encoding=unicode
    RACK_ENV: development
    RAILS_ENV: development
    BUNDLE_PATH: /home/app/.bundle
