---
postgres:
  image: postgres:9.4.2
  ports:
    - "5432:5432"
  volumes:
    - ./docker_compose/postgres-setup:/docker-entrypoint-initdb.d
  environment:
    POSTGRES_PASSWORD: plannr

elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"

web:
  build: ./
  volumes:
    - .:/home/app/plannr
  links:
    - postgres:postgres
    - elasticsearch:elasticsearch
  ports:
    - "3000:3000"
  environment:
    DATABASE_URL: postgres://postgres:plannr@postgres:5432/plannr_development?pool=5&encoding=unicode
    RACK_ENV: development
    RAILS_ENV: development
    BUNDLE_PATH: /home/app/.bundle
