default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || ENV['POSTGRES_PORT'] || 5432 %>
  database: plannr-app_development

test:
  <<: *default
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || ENV['POSTGRES_PORT'] || 5432 %>
  database: plannr-app_test

staging:
  <<: *default
  database: plannr-app_staging
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: /tmp

production:
  <<: *default
  database: plannr-app_production
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
